/**
 * Pixel art matrix models for Byte (Robot), Kraken (Squid), and Neko (Cyber Cat).
 * Matrices are indexed [y][x] with color token characters:
 * '.' = transparent
 * 'B' = primary body color
 * 'D' = dark body / shadow
 * 'L' = light / highlight
 * 'E' = eye / screen color
 * 'P' = pupil / dark eye
 * 'A' = accent color (cyan / neon / gold)
 * 'C' = coffee / gear / tool
 * 'H' = heart / pink
 * 'W' = white
 */

import type { MascotSkin } from './tamagotchi-store.ts'

/** The sprite the mascot shows; also the key of every skin's frame table. */
export type MascotState = 'idle' | 'thinking' | 'streaming' | 'tool' | 'approval' | 'error' | 'success'

/** One skin's colors, indexed by the digits used in its frame rows. */
export interface PixelPalette {
  primary: string
  dark: string
  light: string
  eye: string
  pupil: string
  accent: string
  tool: string
  heart: string
  white: string
}

/** Every skin's palette. */
export const PALETTES: Record<MascotSkin, PixelPalette> = {
  byte: {
    primary: '#4d88ff',
    dark: '#254db3',
    light: '#80adff',
    eye: '#00ffff',
    pupil: '#005577',
    accent: '#ffd700',
    tool: '#ff8800',
    heart: '#ff4d88',
    white: '#ffffff',
  },
  kraken: {
    primary: '#00b4d8',
    dark: '#0077b6',
    light: '#90e0ef',
    eye: '#caf0f8',
    pupil: '#03045e',
    accent: '#48cae4',
    tool: '#f77f00',
    heart: '#ff4d88',
    white: '#ffffff',
  },
  neko: {
    primary: '#8338ec',
    dark: '#5a189a',
    light: '#c77dff',
    eye: '#06d6a0',
    pupil: '#004b39',
    accent: '#ff006e',
    tool: '#ffbe0b',
    heart: '#ff006e',
    white: '#ffffff',
  },
}

// 16x16 sprite frames
const BYTE_FRAMES: Record<MascotState, string[]> = {
  idle: [
    '....AAAA....',
    '....A..A....',
    '...DDDDDD...',
    '..DBBBBBDD..',
    '..DBEEEEBD..',
    '..DBEPEEBD..',
    '..DBEEEEBD..',
    '..DBBBBBDD..',
    '...DDDDDD...',
    '..DBBBBBDD..',
    '.DDBBBBBDDD.',
    '.D.DBBBDD.D.',
    '...DBBBDD...',
    '...DB..DD...',
    '...DD..DD...',
    '............',
  ],
  thinking: [
    '.....WW.....',
    '....WAAW....',
    '...WAAAAW...',
    '....AAAA....',
    '...DDDDDD...',
    '..DBEEEEBD..',
    '..DBE.EEBD..',
    '..DBEEEEBD..',
    '..DBBBBBDD..',
    '...DDDDDD...',
    '..DBBBBBDD..',
    '.DDBBBBBDDD.',
    '.D.DBBBDD...',
    '...DBBBDD.D.',
    '...DD..DD...',
    '............',
  ],
  streaming: [
    '...AA..AA...',
    '...AAAAAA...',
    '...DDDDDD...',
    '..DBEEEEBD..',
    '..DBPEPEBD..',
    '..DBEEEEBD..',
    '..DBBBBBDD..',
    '...DDDDDD...',
    '.ADBBBBBDDA.',
    '.ADBBBBBDDA.',
    '..DBBBBBDD..',
    '.WCCCCCCCW..',
    '.WCCCCCCCW..',
    '...DD..DD...',
    '...DD..DD...',
    '............',
  ],
  tool: [
    '..CCCCCCCC..',
    '..CCCCCCCC..',
    '...DDDDDD...',
    '..DWEEEEWD..',
    '..DWPEPEWD..',
    '..DWEEEEWD..',
    '..DBBBBBDD..',
    '...DDDDDD...',
    '.CDBBBBBDDC.',
    '.CDBBBBBDDC.',
    '..DBBBBBDD..',
    '..CDBBBDDC..',
    '...DBBBDD...',
    '...DD..DD...',
    '...DD..DD...',
    '............',
  ],
  approval: [
    '...WWWWWW...',
    '..WWHAAHWW..',
    '..WWAAAAWW..',
    '....AAAA....',
    '...DDDDDD...',
    '..DBEEEEBD..',
    '..DBEPEEBD..',
    '..DBEEEEBD..',
    '..DBBBBBDD..',
    '...DDDDDD...',
    'A.DBBBBBDD..',
    'ADDBBBBBDDD.',
    'A..DBBBDD...',
    '...DBBBDD.D.',
    '...DD..DD...',
    '............',
  ],
  error: [
    '....AAAA....',
    '....A..A....',
    '...DDDDDD...',
    '..DBBBBBDD..',
    '..DBE..EBD..',
    '..DB.EE.BD..',
    '..DBE..EBD..',
    '..DBBBBBDD..',
    '...DDDDDD...',
    '..DBBBBBDD..',
    '.DDBBBBBDDD.',
    '.D.DBBBDD.D.',
    '...DBBBDD...',
    '...DD..DD...',
    '...DD..DD...',
    '............',
  ],
  success: [
    '.W...AA...W.',
    '..W.AAAA.W..',
    '...DDDDDD...',
    '..DBEEEEBD..',
    '..DBE^^EBD..',
    '..DBEEEEBD..',
    '..DBBBBBDD..',
    '...DDDDDD...',
    'A.DBBBBBDD.A',
    'AADBBBBBDDAA',
    '..DBBBBBDD..',
    '...DBBBDD...',
    '..DDB..BDD..',
    '..DD....DD..',
    '............',
    '............',
  ],
}

const KRAKEN_FRAMES: Record<MascotState, string[]> = {
  idle: [
    '....DDDD....',
    '...DBBBBD...',
    '..DBBBBBBD..',
    '.DBBBBBBBBD.',
    '.DBEEEEEEBD.',
    '.DBEPEEPEBD.',
    '.DBEEEEEEBD.',
    '.DBBBBBBBBD.',
    '..DBBBBBBD..',
    '...DDDDDD...',
    '.DB.DB.BD.BD',
    '.DB.DB.BD.BD',
    '.DD.DD.DD.DD',
    '............',
    '............',
    '............',
  ],
  thinking: [
    '....WWWW....',
    '...WAAAAW...',
    '....AAAA....',
    '...DBBBBD...',
    '..DBBBBBBD..',
    '.DBEEEEEEBD.',
    '.DBE.EE.EBD.',
    '.DBEEEEEEBD.',
    '.DBBBBBBBBD.',
    '..DBBBBBBD..',
    '...DDDDDD...',
    '.DB.DB.BD.BD',
    '.DB.DB.BD.BD',
    '.DD.DD.DD.DD',
    '............',
    '............',
  ],
  streaming: [
    '....DDDD....',
    '...DBBBBD...',
    '..DBBBBBBD..',
    '.DBBBBBBBBD.',
    '.DBEEEEEEBD.',
    '.DBEPEEPEBD.',
    '.DBEEEEEEBD.',
    '.DBBBBBBBBD.',
    '..DBBBBBBD..',
    'W.CCCCCCCC.W',
    'WDB.DB.BD.BD',
    'WDB.DB.BD.BD',
    '.DD.DD.DD.DD',
    '............',
    '............',
    '............',
  ],
  tool: [
    '..CCCCCCCC..',
    '..CCCCCCCC..',
    '..DBBBBBBD..',
    '.DWEEEEEEWD.',
    '.DWEPEEPEWD.',
    '.DWEEEEEEWD.',
    '.DBBBBBBBBD.',
    '..DBBBBBBD..',
    '...DDDDDD...',
    'CDB.DB.BD.BD',
    'CDB.DB.BD.BD',
    '.DD.DD.DD.DD',
    '............',
    '............',
    '............',
    '............',
  ],
  approval: [
    '...WWWWWW...',
    '..WWHAAHWW..',
    '....AAAA....',
    '...DBBBBD...',
    '..DBBBBBBD..',
    '.DBEEEEEEBD.',
    '.DBEPEEPEBD.',
    '.DBEEEEEEBD.',
    '.DBBBBBBBBD.',
    '..DBBBBBBD..',
    'A..DDDDDD...',
    'ADB.DB.BD.BD',
    'ADB.DB.BD.BD',
    '.DD.DD.DD.DD',
    '............',
    '............',
  ],
  error: [
    '....DDDD....',
    '...DBBBBD...',
    '..DBBBBBBD..',
    '.DBBBBBBBBD.',
    '.DBE....EBD.',
    '.DB..EE..BD.',
    '.DBE....EBD.',
    '.DBBBBBBBBD.',
    '..DBBBBBBD..',
    '...DDDDDD...',
    '.DB.DB.BD.BD',
    '.DB.DB.BD.BD',
    '.DD.DD.DD.DD',
    '............',
    '............',
    '............',
  ],
  success: [
    '.W...DD...W.',
    '..W.DBBD.W..',
    '..DBBBBBBD..',
    '.DBBBBBBBBD.',
    '.DBEEEEEEBD.',
    '.DBE^^E^^EBD',
    '.DBEEEEEEBD.',
    '.DBBBBBBBBD.',
    'A.DBBBBBBD.A',
    'A..DDDDDD..A',
    'ADB.DB.BD.BD',
    '.DB.DB.BD.BD',
    '.DD.DD.DD.DD',
    '............',
    '............',
    '............',
  ],
}

const NEKO_FRAMES: Record<MascotState, string[]> = {
  idle: [
    '.DD......DD.',
    '.DBBD..DBBD.',
    '.DBBBBBBBBD.',
    '.DBEEEEEEBD.',
    '.DBEPEEPEBD.',
    '.DBEEEEEEBD.',
    '..DBBHBBDD..',
    '...DDDDDD...',
    '..DBBBBBBD..',
    '.DDBBBBBBDD.',
    '.D.DBBBBDD..',
    '...DB..BD...',
    '...DD..DD...',
    '..........DD',
    '.........DBB',
    '..........DD',
  ],
  thinking: [
    '.....WW.....',
    '....WAAW....',
    '.DD.WAAW.DD.',
    '.DBBD..DBBD.',
    '.DBBBBBBBBD.',
    '.DBEEEEEEBD.',
    '.DBE.EE.EBD.',
    '.DBEEEEEEBD.',
    '..DBBHBBDD..',
    '...DDDDDD...',
    '..DBBBBBBD..',
    '.DDBBBBBBDD.',
    '...DB..BD...',
    '...DD..DD...',
    '.........DBB',
    '..........DD',
  ],
  streaming: [
    '.DD......DD.',
    '.DBBD..DBBD.',
    '.DBBBBBBBBD.',
    '.DBEEEEEEBD.',
    '.DBEPEEPEBD.',
    '.DBEEEEEEBD.',
    '..DBBHBBDD..',
    '...DDDDDD...',
    '.ADBBBBBDDA.',
    '.ADBBBBBDDA.',
    '.WCCCCCCCW..',
    '...DB..BD...',
    '...DD..DD...',
    '.........DBB',
    '..........DD',
    '............',
  ],
  tool: [
    '..CCCCCCCC..',
    '..CCCCCCCC..',
    '.DBBBBBBBBD.',
    '.DWEEEEEEWD.',
    '.DWEPEEPEWD.',
    '.DWEEEEEEWD.',
    '..DBBHBBDD..',
    '...DDDDDD...',
    '.CDBBBBDDC..',
    '..DBBBBBBD..',
    '...DB..BD...',
    '...DD..DD...',
    '.........DBB',
    '..........DD',
    '............',
    '............',
  ],
  approval: [
    '...WWWWWW...',
    '..WWHAAHWW..',
    '.DD.AAAA.DD.',
    '.DBBD..DBBD.',
    '.DBBBBBBBBD.',
    '.DBEEEEEEBD.',
    '.DBEPEEPEBD.',
    '.DBEEEEEEBD.',
    '..DBBHBBDD..',
    'A..DDDDDD...',
    'ADDBBBBBBDD.',
    '...DB..BD...',
    '...DD..DD...',
    '.........DBB',
    '..........DD',
    '............',
  ],
  error: [
    '.DD......DD.',
    '.DBBD..DBBD.',
    '.DBBBBBBBBD.',
    '.DBE....EBD.',
    '.DB..EE..BD.',
    '.DBE....EBD.',
    '..DBBHBBDD..',
    '...DDDDDD...',
    '..DBBBBBBD..',
    '.DDBBBBBBDD.',
    '...DB..BD...',
    '...DD..DD...',
    '.........DBB',
    '..........DD',
    '............',
    '............',
  ],
  success: [
    '.W...DD...W.',
    '..W.DBBD.W..',
    '.DBBBBBBBBD.',
    '.DBEEEEEEBD.',
    '.DBE^^E^^EBD',
    '.DBEEEEEEBD.',
    '..DBBHBBDD..',
    'A..DDDDDD..A',
    'AADBBBBBBDDA',
    '..DBBBBBBD..',
    '..DDB..BDD..',
    '..DD....DD..',
    '.........DBB',
    '..........DD',
    '............',
    '............',
  ],
}

/**
 * The sprite rows for one skin in one state.
 * @param skin - the selected mascot skin.
 * @param state - the mascot state to draw.
 * @returns the frame's rows, one string of palette indices per pixel row.
 */
export function getMascotFrame(skin: MascotSkin, state: MascotState): string[] {
  switch (skin) {
    case 'kraken': return KRAKEN_FRAMES[state]
    case 'neko': return NEKO_FRAMES[state]
    case 'byte': return BYTE_FRAMES[state]
  }
}
